[package]
name = "lix"
version = "0.1.0"
authors = ["oraqlle <tyler.swann05@gmail.com>"]
edition = "2021"

[dependencies]
rustyline = "11.0.0"

# [lib]
# name = "lix"
# path = "src/lib/lix.rs"

[[bin]]
name = "lix"
path = "src/bin/main.rs"
